[phases.setup]
nixPkgs = ["python312", "ffmpeg"]

[phases.install]
# Usamos el path completo al pip del entorno virtual de Railway
cmds = ["/app/.venv/bin/pip install -r requirements.txt"]

[start]
# Usamos el python del entorno virtual para arrancar el bot
cmd = "/app/.venv/bin/python radiobot.py"
